# This workflow will run tests using node and then publish a package to GitHub Packages when push to master

name: publish package

on:
  push:
    branches:
      - master
      - 'feature/HOT-913'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
